### ISSUE TITLE
Tier 2 abstract interpreter for the optimizer

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#107557]
# Feature or enhancement
(Mega issue) Start doing optimization passes on tier 2 bytecode.

# Pitch
The target of tier 2 optimizations is tier 2 bytecode. Abstract interpretation is a natural way to analyze and optimize tier 2 bytecode. We can generate the abstract interpreter from the bytecode DSL

# Previous discussion
See https://github.com/faster-cpython/ideas/issues/611

# Todo list:
- [ ] Generate a barebones tier 2 abstract interpreter from the DSL.
- [ ] Set up the abstract interpreter. This requires that we pass in the runtime state at the point of entering the executor.
- [ ] Perform partial evaluation. For now, all `static` comes from `LOAD_CONST`. Assume everything else is `dynamic`.

The initial partial evaluation will be bad because it does not have that much `static` information (we need watchers for methods, functions, global, etc., to make them effectively static). However, that phase can be done in the region formation step before partial evaluation. Someone else can pick them up as a parallel workstream.

### Linked PRs
* gh-107558
* gh-107847
* gh-108583

**Comment by Fidget-Spinner** [comment]
I now have a clearer idea of what I'm going to do. I'm abandoning this issue and re-creating a new one since most of the description is outdated.
