### ISSUE TITLE
Docs: the calendar module lacks documentation for several APIs

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#108202]
> But first than documenting these particular method or two, we should decide whether they should be documented at all.
>
> See past issues with the `calendar` module. There may be requests for undocumented methods, and some of them may even be rejected already. I think this has already been discussed.

_Originally posted by @serhiy-storchaka in https://github.com/python/cpython/pull/108192#discussion_r1299892823_

### Linked PRs
* gh-108398
* gh-108467
* gh-108468
* gh-108466
* gh-108492
* gh-108579
* gh-109020
* gh-109030
* gh-109031
* gh-127579
* gh-127608
* gh-128440
* gh-128441
* gh-128564
* gh-128565
* gh-128566
* gh-128579
* gh-128580

**Comment by AA-Turner** [comment]
*(status as at 21c0844)*

Defined in ``__all__`` but not documented
-----------------------------------------

- ``IllegalMonthError``
- ``IllegalWeekdayError``
- ``JANUARY``, etc (These are documented as ``Month.X``, but also exist in the module scope)
- ``MONDAY``, etc (These are documented as ``Day.X``, but also exist in the module scope)

Undocumented methods
--------------------

- ``Calendar.getfirstweekday()``
- ``Calendar.setfirstweekday()``
- ``Calendar.firstweekday``

- ``TextCalendar.prweek()``
- ``TextCalendar.formatday()
- ``TextCalendar.formatweek()
- ``TextCalendar.formatweekday()
- ``TextCalendar.formatweekheader()
- ``TextCalendar.formatmonthname()

- ``HTMLCalendar.cssclasses
- ``HTMLCalendar.
- ``HTMLCalendar.
- ``HTMLCalendar.
- ``HTMLCalendar.





- ``HTMLCalendar.formatmonthname``
- ``formatweekday``
- ``formatmonthname``

**Comment by AA-Turner** [comment]
*(status as at 21c0844)*

Defined in ``__all__`` but not documented
=========================================

- [X] ``IllegalMonthError`` (#108398)
- [X] ``IllegalWeekdayError`` (#108398)
- [x] ``JANUARY``, etc (These are documented as ``Month.X``, but also exist in the module scope) (#108492)
- [x] ``MONDAY``, etc (These are documented as ``Day.X``, but also exist in the module scope) (#108492)

Undocumented classes
======================

- ``different_locale`` (should not be documented, helper class)

Undocumented functions
======================

- [ ] ``prweek()``
- [ ] ``week()``
- [ ] ``format()``
- [ ] ``formatstring()``

Undocumented methods
====================

Calendar
--------

- [x] ``Calendar.getfirstweekday()``
- [x] ``Calendar.setfirstweekday()``
- [x] ``Calendar.firstweekday``: (#128566)

TextCalendar
------------

- [ ] ``TextCalendar.prweek()`` (#108466)
- [x] ``TextCalendar.formatday()`` (#128353)
- [x] ``TextCalendar.formatweek()``
- [x] ``TextCalendar.formatweekday()``
- [x] ``TextCalendar.formatweekheader()``
- [x] ``TextCalendar.formatmonthname()``

HTMLCalendar
------------

- [ ] ``HTMLCalendar.formatday()``
- [ ] ``HTMLCalendar.formatweek()``
- [ ] ``HTMLCalendar.formatweekday()``
- [ ] ``HTMLCalendar.formatweekheader()``
- [x] ``HTMLCalendar.formatmonthname()``

Undocumented attributes
=======================

- ``EPOCH`` (should not be documented, of no use)
- ``mdays`` (should not be documented, of no use)

Undocumented miscellany
=======================

- [x] ``python -m calendar`` (``main()``) (#109020)

A

**Comment by AA-Turner** [comment]
I think at the least we ought document ``IllegalMonthError`` and ``IllegalWeekdayError``, I'll open a PR shortly.

A

**Comment by erlend-aasland** [comment]
I think I managed to dig up the discussion @serhiy-storchaka was referring to in [his previous comment](https://github.com/python/cpython/pull/108192#discussion_r1299892823):

- https://mail.python.org/archives/list/python-dev@python.org/thread/SJWR73UOGRSVC3HKHR4SZEJ3KINH32PQ/#ACNDSI6FN6DZKOASNZS4AEQJWWXL6F7Q

See also:

- https://mail.python.org/archives/list/python-dev@python.org/thread/UEKY2MA6MFHP2KQ6B6TMFWXETRAOWGU5/#URCWZKVYAF3S6URR4RWUAMFMQHSMI3IU
- https://github.com/python/cpython/issues/72479#issuecomment-1093728179 (and the following discussion and PR)

**Comment by erlend-aasland** [comment]
I removed the `easy` label. Adding docs for the `calendar` module is controversial. Please read the OP and https://github.com/python/cpython/issues/108202#issuecomment-2515583744.
