### ISSUE TITLE
User-defined virtual path objects

### ISSUE THREAD

**Issue by barneygale** [python/cpython#110109]
## Proposal

Add a `PathBase` class that can be subclassed by users to implement "virtual paths", e.g. paths within `.zip` files or on FTP servers, and publish it as an external PyPI package.

## Phase 1: Private support in pathlib

- [x] Add private `_PathBase` class 
  - #106337
- [x] Merge `WalkTests` into `DummyPathTest` 
  - #110308
  - #110655
- [x] Sort out `__hash__()`, `__eq__`, etc - we shouldn't inherit the `PurePath` implementation
  - #112012 
  - #110670 
- [x] Simplify/speed up path walking and globbing
  - #106703
- [x] Add `from_uri()` classmethod
  - #107640

## Phase 2: Experimental support in PyPI package

- [x] Move ABCs into `pathlib._abc`
  - #112881
  - #112904
- [x] Figure out the default value for `pathmod`, if any
  - #113221
  - #113219
- [x] Publish PyPI package

## Previous Discussion

https://discuss.python.org/t/make-pathlib-extensible/3428

### Linked PRs
* gh-110308
* gh-110312
* gh-110321
* gh-110412
* gh-110655
* gh-110670
* gh-112012
* gh-112239
* gh-112242
* gh-112881
* gh-112901
* gh-112904
* gh-113219
* gh-113221
* gh-113292
* gh-113376
* gh-113411
* gh-113417
* gh-113419

**Comment by barneygale** [comment]
Nearly ready. Final two PRs:

- https://github.com/python/cpython/pull/113417
- https://github.com/python/cpython/pull/113419

**Comment by barneygale** [comment]
`pathlib-abc==0.1.0` available now! https://pypi.org/project/pathlib-abc/0.1.0/
