### ISSUE TITLE
Issues from docs@python.org

### ISSUE THREAD

**Issue by encukou** [python/cpython#110383]
Users who don't have a github login are instructed to report issues to docs@python.org.
I meant to do some triaging before converting the mails to GH issues, but always had something more important to do. So I'm posting a rough list to get more eyes on these. Each has a link to the list post.

(These weren't triaged; they're not necessarily good ideas.)

```[tasklist]
### Tasks
- [x] typo in socket docs -- [Hank Knox](https://mail.python.org/archives/list/docs@python.org/thread/T7BAG3ROH3YT3YTAWCUE7CMZ2FI6VO72/)
- [x] asyncio shield typo -- [Dyussenov Nuraly](https://mail.python.org/archives/list/docs@python.org/thread/6EM4DHHS3RMWSJWV2ZGKWTJRD4Z2GNIC/) - (https://github.com/python/cpython/pull/108427)
- [x] array -- data type range printed wrong -- [Shivansh Verma](https://mail.python.org/archives/list/docs@python.org/thread/B463UYLY2RBIG66LXM3TIPZDZIYWCN6X/) (#113708)
- [ ] EPUB error -- e.g. [Glenn Street](https://mail.python.org/archives/list/docs@python.org/thread/HSIILYH7LVK4JU5U5GWHHIP4PU34UTNN/), [Ranjith B](https://mail.python.org/archives/list/docs@python.org/thread/Y3K22WC7QQVIECZBLFZPYYFWOCAOPZ2K/), [sobi](https://mail.python.org/archives/list/docs@python.org/message/JELSGFZ6HC2SKHPHTX3LSGH627QVGE5N/)
- [x] Howto/regex omits the simplest {n} case -- [Derek Mead](https://mail.python.org/archives/list/docs@python.org/thread/7D56UZ3VSWCQVQPIL44LWTO42EJUBRKI/) -- (https://github.com/python/cpython/pull/111110)
- [x] Problem in help for str().rsplit() -- [Alan Brogan](https://mail.python.org/archives/list/docs@python.org/thread/MCSKKTHBKX6AIK25YI2INEDVONJZYRLH/) - (https://github.com/python/cpython/pull/113355)
- [x] replacement for deprecation -- [SUN Guonian](https://mail.python.org/archives/list/docs@python.org/thread/4AYZNSW3RB3DNT5C7JEE6RCESBWIKZTD/) (https://github.com/python/cpython/pull/112783)
- [x] Potential typo in Profiler docs? -- [2dfkit](https://mail.python.org/archives/list/docs@python.org/thread/DJNXVVP2UW4R6OAPRA6TE5WMHDC4NKZ6/)
- [x] timeit -- [Arthur Goldberg](https://mail.python.org/archives/list/docs@python.org/thread/CQON3MGDEN6CY5KFXXBY4FTCG2FIIDTM/) -- (GH-110407)
- [x] list of errata: 1 -- [Stephan Stiller](https://mail.python.org/archives/list/docs@python.org/thread/ZEDPZHRVGLYR4ZFZ5I3NBWVMHMX4WPGW/)
- [x] list of errata: 2 -- [Stephan Stiller](https://mail.python.org/archives/list/docs@python.org/thread/ZEDPZHRVGLYR4ZFZ5I3NBWVMHMX4WPGW/) -- (https://github.com/python/cpython/pull/119330)
- [x] list of errata: 3 -- [Stephan Stiller](https://mail.python.org/archives/list/docs@python.org/thread/ZEDPZHRVGLYR4ZFZ5I3NBWVMHMX4WPGW/) -- (https://github.com/python/cpython/pull/112777)
- [x] list of errata: 4 -- [Stephan Stiller](https://mail.python.org/archives/list/docs@python.org/thread/ZEDPZHRVGLYR4ZFZ5I3NBWVMHMX4WPGW/) - WONTFIX
- [x] list of errata: 5 -- [Stephan Stiller](https://mail.python.org/archives/list/docs@python.org/thread/ZEDPZHRVGLYR4ZFZ5I3NBWVMHMX4WPGW/) - WONTFIX
- [x] list of errata: 6 -- [Stephan Stiller](https://mail.python.org/archives/list/docs@python.org/thread/ZEDPZHRVGLYR4ZFZ5I3NBWVMHMX4WPGW/) -- (#120219)
- [x] list of errata: 7 -- [Stephan Stiller](https://mail.python.org/archives/list/docs@python.org/thread/ZEDPZHRVGLYR4ZFZ5I3NBWVMHMX4WPGW/)
- [x] list of errata: 8 -- [Stephan Stiller](https://mail.python.org/archives/list/docs@python.org/thread/ZEDPZHRVGLYR4ZFZ5I3NBWVMHMX4WPGW/) -- (https://github.com/python/cpython/pull/111574)
- [x] list of errata: 9 -- [Stephan Stiller](https://mail.python.org/archives/list/docs@python.org/thread/ZEDPZHRVGLYR4ZFZ5I3NBWVMHMX4WPGW/)
- [x] profiler docs inaccuracy -- [2dfkit](https://mail.python.org/archives/list/docs@python.org/thread/DJNXVVP2UW4R6OAPRA6TE5WMHDC4NKZ6/#DJNXVVP2UW4R6OAPRA6TE5WMHDC4NKZ6) -- (https://github.com/python/cpython/pull/112221)
- [ ] https://github.com/python/cpython/issues/112146
- [x] Getting tkinter -- [Steve Philcox](https://mail.python.org/archives/list/docs@python.org/message/JOQ3RQVG3A7ZYOWEVU7TAYLY2WSZ6TST/): This complaint is about how to install dependencies when building CPython; this is already covered by the devguide.
- [ ] https://github.com/python/cpython/issues/120302
- [x] Problems in Python tutorial -- [Todd Hoatson](https://mail.python.org/archives/list/docs@python.org/message/REO4QRDIHU5ML4BMNXPDONCKONIH6RN3/)
- [x] link from UserList docs to the collections classes list of methods -- [Seebs](https://mail.python.org/archives/list/docs@python.org/message/37ZRBCHCB37Y2KW73EBHXFGRIZHFCNUU/) - WONTFIX
- [x] confusing formatting of “`field`s” -- [Роман Филимонов](https://mail.python.org/archives/list/docs@python.org/message/G5AYM2N4LLB65BTPQZBX5BIMBXRGUPVP/): this is a common way of marking up the plural variant of something that's marked up using a monospaced font; not a bug
- [x] socket.makefile -- [Michael Gold](https://mail.python.org/archives/list/docs@python.org/thread/3VGLA6Q6QDYB7XIAHFIRAVW4TQSEAZGA/)
- [x] `pow` - “integral” is confusing to non-natives -- [marc rovira](https://mail.python.org/archives/list/docs@python.org/thread/HD47WPHMLKUTQEWEQOHBAGULUHN4ICPQ/) -- (https://github.com/python/cpython/pull/119688)
```

Feel free to tick off ones that aren't appropriate, and convert larger ones to their own issues.

### Linked PRs
* gh-110407
* gh-110409
* gh-110410
* gh-110434
* gh-110435
* gh-110436
* gh-111018
* gh-111110
* gh-111204
* gh-111205
* gh-111206
* gh-111207
* gh-111208
* gh-111247
* gh-112221
* gh-112262
* gh-112263
* gh-111574
* gh-112264
* gh-112265
* gh-112777
* gh-112783
* gh-113353
* gh-113355
* gh-113379
* gh-113380
* gh-113708
* gh-118970
* gh-119150
* gh-119230
* gh-119324
* gh-119325
* gh-119326
* gh-119327
* gh-119330
* gh-119370
* gh-119371
* gh-119688
* gh-120206
* gh-120207
* gh-120219
* gh-120229
* gh-120230

**Comment by Paulie-Aditya** [comment]
Could I get this assigned to me?

**Comment by Unique-Usman** [comment]
Asyncio shield typo - solved.
Problem in help for str().rsplit()  - solved. 
list of errata: 9 - solved. 
list of errata:  8- solved. 
list of errata:  7 - solved. 
list of errata:  2 - solved. 

These tasks has been solved @hugovk. Some changes has not yet reflected on the Doc page.

**Comment by hugovk** [comment]
Thanks for checking!

> Asyncio shield typo - solved.

This was fixed in https://github.com/python/cpython/pull/108427 but not backported. I'm backporting now: https://github.com/python/cpython/pull/111244, https://github.com/python/cpython/pull/111245.

**Comment by hugovk** [comment]
> Problem in help for str().rsplit() - solved.

This still exists, it's in the docstring: https://github.com/search?q=repo%3Apython%2Fcpython%20%22starting%20from%20the%20left%22&type=code

**Comment by hugovk** [comment]
> list of errata: 9 - solved. 

Fixed in https://github.com/python/cpython/pull/107386.

> list of errata: 8- solved. 

Still present.

> list of errata: 7 - solved. 

I don't see the reported problem -- `buffering=- 1` -- nor the suggested solution -- `buffering= -1`. Instead I see `buffering=-1` which looks correct. Perhaps the problem is only on a certain browser? I'm using Chrome on macOS. Anyway, let's mark as solved.

> list of errata: 2 - solved.

Not solved, but they're suggesting replacing `get(key[, default])` with `get(key[, default=None])`.

We've had discussions around this sort of thing, and I'm not sure about this one.

**Comment by Unique-Usman** [comment]
> > Problem in help for str().rsplit() - solved.
> 
> This still exists, it's in the docstring: https://github.com/search?q=repo%3Apython%2Fcpython%20%22starting%20from%20the%20left%22&type=code

I have fixed it now, now this is the pull request - (https://github.com/python/cpython/pull/111247#ref-issue-1927870489). Help check. Also to note, I changed the 'left' to 'right' for the str.rpslit Doc only. The str.split should start from the left.

**Comment by Unique-Usman** [comment]
> > list of errata: 9 - solved.
> 
> Fixed in #107386.
> 
> > list of errata: 8- solved.
> 
> Still present.
> 
> > list of errata: 7 - solved.
> 
> I don't see the reported problem -- `buffering=- 1` -- nor the suggested solution -- `buffering= -1`. Instead I see `buffering=-1` which looks correct. Perhaps the problem is only on a certain browser? I'm using Chrome on macOS. Anyway, let's mark as solved.
> 
> > list of errata: 2 - solved.
> 
> Not solved, but they're suggesting replacing `get(key[, default])` with `get(key[, default=None])`.
> 
> We've had discussions around this sort of thing, and I'm not sure about this one.

Ohh, yeah, the reported problem was present on my Linux machine with Chrome browser, but, it is`buffering=-1` in the repo which is correct.

**Comment by zware** [comment]
> > list of errata: 7 - solved.
> 
> I don't see the reported problem -- `buffering=- 1` -- nor the suggested solution -- `buffering= -1`. Instead I see `buffering=-1` which looks correct. Perhaps the problem is only on a certain browser? I'm using Chrome on macOS. Anyway, let's mark as solved.

It is (was) a theme issue: see #96056, #98444.

**Comment by zware** [comment]
> Thanks for checking!
> 
> > Asyncio shield typo - solved.
> 
> This was fixed in #108427 but not backported. I'm backporting now: #111244, #111245.

This was also reverted in GH-111271 and friends :).  I've opened gh-111274 to deal with this one on its own.

**Comment by aptakhin** [comment]
Hello, I added [PR](https://github.com/python/cpython/pull/112221) to fix this item: 
> profiler docs inaccuracy -- [2dfkit](https://mail.python.org/archives/list/docs@python.org/thread/DJNXVVP2UW4R6OAPRA6TE5WMHDC4NKZ6/#DJNXVVP2UW4R6OAPRA6TE5WMHDC4NKZ6)

**Comment by hugovk** [comment]
Thanks!

I've marked both of these as done because I think they're the same thing. Let me know if not.

- [x] Potential typo in Profiler docs? -- [2dfkit](https://mail.python.org/archives/list/docs@python.org/thread/DJNXVVP2UW4R6OAPRA6TE5WMHDC4NKZ6/)
- [x] profiler docs inaccuracy -- [2dfkit](https://mail.python.org/archives/list/docs@python.org/thread/DJNXVVP2UW4R6OAPRA6TE5WMHDC4NKZ6/#DJNXVVP2UW4R6OAPRA6TE5WMHDC4NKZ6) -- (https://github.com/python/cpython/pull/112221)

**Comment by Unique-Usman** [comment]
Hi @hugovk help review this https://github.com/python/cpython/pull/111574

**Comment by hugovk** [comment]
> list of errata: 1 -- [Stephan Stiller](https://mail.python.org/archives/list/docs@python.org/thread/ZEDPZHRVGLYR4ZFZ5I3NBWVMHMX4WPGW/)

This is:

> 1.
> https://docs.python.org/3/tutorial/controlflow.html
> I think it would be better if there were a pastable space after "144 233
> 377 610 987 1597" (and in some other places in the tutorial). My guess is
> that the present formatting has to do with the way these pages are
> generated.

I don't think there's anything actionable here, I'll check it off the list.

**Comment by uatach** [comment]
@hugovk I've just created PR #118970

**Comment by squeakyboots** [comment]
> * socket.makefile -- [Michael Gold](https://mail.python.org/archives/list/docs@python.org/thread/3VGLA6Q6QDYB7XIAHFIRAVW4TQSEAZGA/)
> *

Further documented that combined file modes are supported.
https://github.com/python/cpython/pull/119150

**Comment by johnlandonwood** [comment]
Hey y'all, first time contributor here. I've opened PR #119330 for "list of errata: 2".

**Comment by adiaholic** [comment]
Hello, I've submitted a pull request addressing two of the issues mentioned earlier. 
Please feel free to review it at your convenience and let me know if there are any adjustments you'd like me to make.

**Comment by erlend-aasland** [comment]
Regarding the [PDF readability](https://mail.python.org/archives/list/docs@python.org/message/ER3QIEGI63L4C4N2Q5I6GJHBYU5UZGG7/) issue:

> [...] I appreciate the wealth of information in the Python documentation but have encountered challenges with the *PDF format. Specifically, the code sample readability is hindered, making it hard to highlight* and annotate effectively. *Please have a look at the picture attached , you will find the code sample hard to read.*
>
> To enhance accessibility, I suggest optimizing code sample color contrast.
This improvement would benefit users across preferences and ensure a more
user-friendly experience.

The image attached to that report, is attached here:

<details>

![image](https://github.com/python/cpython/assets/13780613/91932932-7538-4d1f-b091-5167b91ff672)

</details>

I downloaded the docs as PDF, and currently they're rendered like this:

<details>

<img width="860" alt="Screenshot 2024-06-07 at 12 57 39" src="https://github.com/python/cpython/assets/13780613/847c4207-33ef-4128-8850-311f7dcc50c2">

</details>

IMO, there is an improvement, but I'm not sure if it's a good enough improvement. Comments? It sounds to me this may be better handled as a separate issue.

**Comment by hugovk** [comment]
The 4.43:1 contrast ratio of green digits on grey is much better than before, but doesn't quite meet the WCAG AA guidelines of 4.5:1.

https://webaim.org/resources/contrastchecker/?fcolor=247F51&bcolor=F2F2F2

The grey symbols (5.12:1) meets AA and the black text (18.75:1) meets both AA and AAA (7:1).

I'm not sure where these colours are defined.

**Comment by erlend-aasland** [comment]
> I'm not sure where these colours are defined.

Me neither, but ISTM the PDFs are generated from `make -C Doc dist`. I'm suspecting it might be the Sphinx LaTeX package `sphinx.sty`.

**Comment by erlend-aasland** [comment]
@encukou: I suggest creating separate, and more actionable, issues of the EPUB and PDF readability reports. I think the two remaining issues reports by Stiller are non-issues; the first is talking about IDLE in a tutorial that is using the REPL, and I'm not sure the remaining issue is worth trying to solve. Regarding the "UserList" issue, I have no opinion.

In the future, I think it would be better to _not_ collect multiple unrelated reports into one issue, like it's done here; such an umbrella issue has an enormous risk of quickly turning stale. IMO, it is better for the reporters, for the triagers, and for contributors, if we break these up into single more actionable and easily triaged issues :)

**Comment by encukou** [comment]
> I suggest creating separate, and more actionable, issues of the EPUB and PDF readability reports.

Please do make an issue! GitHub has a button to do that in the ⋯ menu.

> IMO, it is better for the reporters, for the triagers, and for contributors, if we break these up into single more actionable and easily triaged issues

When I did that, I was too tempted to *triage* each of the reports, which resulted in a big backlog. Converting from email to GitHub needs to take me less than a minute; otherwise, on a busy day I'll leave it to [“some day when I have time”](https://en.wikipedia.org/wiki/Never).

**Comment by hugovk** [comment]
> I think the two remaining issues reports by Stiller are non-issues; the first is talking about IDLE in a tutorial that is using the REPL, and I'm not sure the remaining issue is worth trying to solve.

I've checked these off as WONTFIX.

> Regarding the "UserList" issue, I have no opinion.

Same, and no-one else has had a go, so I've checked this off as WONTFIX too.

We've got new issues for some of these things, I think we can close this issue now, thanks everyone for helping out!
