### ISSUE TITLE
Make `list` objects thread-safe in `--disable-gil` builds

### ISSUE THREAD

**Issue by colesbury** [python/cpython#112087]
# Feature or enhancement

I expect this to be implemented across multiple PRs.

For context, here is the change from the `nogil-3.12` fork, but things might be done a bit differently in CPython 3.13: https://github.com/colesbury/nogil-3.12/commit/df4c51f82b.

- [x] Most operations should acquire the list object lock using the critical section API.
- [x] Accessing a single element should optimistically avoid locking for performance
- [x] Iterators need some special handling
- [x] list.sort

### Iterators

For performance reasons, we don't want to acquire locks while iterating over lists. This means that list iterators have a lesser notion of thread-safety: multiple threads concurrently using the same *iterator* should not crash but may revisit elements. We should make clear in the documentation that iterators are not generally thread-safe. From an implementation point of view, we should use relaxed atomics to update the `it_index` variable.

Additionally, we don't want to clear the `it_seq` reference to the list when the iterator is exhausted in `--disable-gil` builds. Doing so would pose thread-safety issues (in the "may segfault sense").

I don't expect this to pose any issues for real code. While it's fairly common to share lists between threads, it's rare to share the same iterator object between threads.

### Linked PRs
* gh-113764
* gh-113863
* gh-114268
* gh-114582
* gh-114651
* gh-114843
* gh-114916
* gh-115471
* gh-115472
* gh-115605
* gh-115854
* gh-115875
* gh-116233
* gh-116237
* gh-116353
* gh-116529
* gh-116553
* gh-117438

**Comment by Lincoln-developer** [comment]
Hey, I would love to work on this issue if you don't mind, thanks.

**Comment by colesbury** [comment]
Thanks @Lincoln-developer! I'd suggest starting by transforming some of the functions to use the critical section API. Some  functions that use Argument Clinic can just use the `@critical_section` directive. Other functions will need manual `Py_BEGIN_CRITICAL_SECTION()` and `Py_END_CRITICAL_SECTION()` calls. Feel free to tag me on a draft PR if you would like early feedback.

**Comment by corona10** [comment]
@colesbury Since this work is not updated from last year November, can I assign this issue to myself?

**Comment by colesbury** [comment]
@Lincoln-developer are you still working on this or can @corona10 take this over?

**Comment by Lincoln-developer** [comment]
I think he can take it on because l have taken longer than expected ,its okay

**Comment by Lincoln-developer** [comment]
My apologies for not delivering as expected,

**Comment by corona10** [comment]
## TODO based on diff
- [ ] PyList_SetItem
- [ ] PyList_Append
- [ ] list_repr
- [ ] list_contains
- [ ] list_item
- [ ] list_slice
- [ ] PyList_GetSlice
- [ ] list_concat
- [ ] list_repeat
- [ ] _list_clear
- [ ] list_ass_slice
- [ ] list_inplace_repeat
- [ ] list_ass_item
- [ ] list_insert_impl
- [ ] list_clear_impl
- [ ] list_copy_impl
- [ ] list_append
- [ ] list_extend
- [ ] list_pop_impl
- [ ] list_reverse_impl
- [ ] PyList_Reverse
- [ ] PyList_AsTuple
- [ ] list_index_impl
- [ ] list_count
- [ ] list_remove
- [ ] list_richcompare
- [ ] list___sizeof___impl
- [ ] list_subscript
- [ ] list_ass_subscript
- [ ] listiter_next
- [ ] listiter_len
- [ ] listreviter_next
- [ ] listreviter_len
- [ ] listiter_reduce_general

**Comment by corona10** [comment]
Not to forget: https://github.com/python/cpython/pull/113863/files#r1449145544

**Comment by colesbury** [comment]
@corona10 - there's a duplicate critical section in `list.insert`:

https://github.com/python/cpython/blob/7fa511ba576b9a760f3971ad16dbbbbf91c3f39c/Objects/listobject.c#L804-L826

https://github.com/python/cpython/blob/7fa511ba576b9a760f3971ad16dbbbbf91c3f39c/Objects/listobject.c#L820

**Comment by eendebakpt** [comment]
When looking at the list of items to be made thread safe (https://github.com/python/cpython/issues/112087#issuecomment-1879550899) I noticed that `PyList_GetItem` is not included. I believe it is not thread-safe, since between checking the validity of the index and actually getting at item from the list, the list size could be changed in another thread.

Should `PyList_GetItem` be made thread-safe? Maybe not, since we do not make the full C api thread safe, but only the python interface. From the python side indexing is done via `list_subscript`, which will be made thread safe.

If  `PyList_GetItem`  is not thread-safe, should this be in the documentation somehow? Or perhaps only mark the methods that are thread-safe.

**Comment by erlend-aasland** [comment]
@eendebakpt, see also: https://github.com/capi-workgroup/decisions/issues/9

**Comment by corona10** [comment]
> When looking at the list of items to be made thread safe (https://github.com/python/cpython/issues/112087#issuecomment-1879550899) I noticed that PyList_GetItem is not included.

Well, in @colesbury 's implementation, there was no change about this.
Sam can explain what is the best way.
From my view, it should be thread-safe for seamless migration for 3rd party libraries.

**Comment by corona10** [comment]
'Accessing a single element should optimistically avoid locking for performance' is left, I will take a look tonight.

**Comment by corona10** [comment]
One thing left: https://github.com/python/cpython/pull/116353#discussion_r1513612860

**Comment by corona10** [comment]
@colesbury 
Let's close the issue. I'm not 100% sure it will be safe in true GIL disabled mode, but let's see, and we can fix them later.
