### ISSUE TITLE
Unvendor `libmpdec` sources

### ISSUE THREAD

**Issue by zware** [python/cpython#115119]
To facilitate cleaner updates of the externally-maintained `libmpdec` required by the `_decimal` module, we should migrate away from the bundled copy in `Modules/_decimal/libmpdec` and towards an "external" in `cpython-source-deps` for Windows and `--with-system-libmpdec` by default elsewhere.

My tentative plan is as follows:
- In 3.13:
  - [x] Add `mpdecimal-2.5.1` and `mpdecimal-4.0.0` to `cpython-source-deps`:
       - https://github.com/python/cpython-source-deps/pull/32
       - https://github.com/python/cpython-source-deps/tree/mpdecimal
  - [x] Switch Windows build to `mpdecimal-2.5.1` external (#115182)
  - [x] #115406
  - [x] python/devguide#1313
  - [x] #118382 
  - [x] #118506
  - [x] Update macOS build to `mpdecimal-4.0.0`
  - [x] #118539
  - [x] #118631 
  - [x] ~~Post `#118539`: amend Ubuntu CI to use system installed mpdecimal~~
  - [x] Update the docs; see https://github.com/python/cpython/issues/115119#issuecomment-2089754385
    - https://github.com/python/cpython/pull/136205
    - https://github.com/python/devguide/pull/1598
    - https://github.com/python/cpython/pull/139318
  - [x] #119196
- In 3.15:
  - [x] Defer removal of bundled libmpdec in 3.15: https://github.com/python/cpython/pull/133997
  - [x] Remove the implicit fallback to the bundled copy, keep support for explicit `--without-system-libmpdec` (with warning): #134078
- In 3.16:
  - [ ] Remove `--with[out]-system-libmpdec` `configure` options and `Modules/_decimal/libmpdec/`: #133964

### Linked PRs
* gh-115182
* gh-115406
* gh-118382
* gh-118506
* gh-118539
* gh-118631
* gh-118634
* gh-119196
* gh-119217
* gh-133964
* gh-133997
* gh-134078
* gh-135568
* gh-136199
* gh-136201
* gh-136205
* gh-136239
* gh-136244
* gh-136245
* gh-139318
* gh-139347
* gh-139348
* gh-140077

**Comment by erlend-aasland** [comment]
> [...] with a fallback to the bundled copy (maybe with a warning?)

+1 for an autoconf warning.

**Comment by ned-deily** [comment]
Adding an external libmpdec to the macOS installer build shouldn't be a big issue. Assign it to me if you proceed with this.

**Comment by erlend-aasland** [comment]
FTR: the source deps repo is now updated.

**Comment by erlend-aasland** [comment]
@ned-deily: for build-installer.py, is there more to do than adding a configuration for mpdecimal? I've used the following `configure` options: `['--disable-cxx', 'MACHINE=universal']`

**Comment by ned-deily** [comment]
Likely yes, I'll take care of it. Thanks.

**Comment by ned-deily** [comment]
I took a quick look at this and be aware that this change proposal will likely impact everyone building Python 3.13 on macOS. macOS does not ship a copy of libmpdec so, if the bundled version is removed, anyone building Python on macOS will now need to provide a local copy, either building from source or using a version from one of the widely-used third-party package managers, like Homebrew or MacPorts. Both currently have `mpdecimal` packages at the 4.0.0 level. (Recall that, unlike Windows builds, we do not currently provide non-vendored third-party library binaries for macOS users, other than those built for and linked into the Pythons provided by python.org installers for macOS.) In a quick test, it appeared that with `./configure --with-system-libmpdec` today, `pkg-config` info for `libmpdec` was not being used. If so, that should be corrected. And, in any case, the [devguide instructions for installing dependencies](https://devguide.python.org/getting-started/setup-building/#install-dependencies) will need to be updated to cover libmpdec. We should add all this and get this working before moving on to changing the installer.

**Comment by erlend-aasland** [comment]
> In a quick test, it appeared that with `./configure --with-system-libmpdec` today, `pkg-config` info for `libmpdec` was not being used. If so, that should be corrected.

Last time I checked, libmpdec did not provide pkgconfig files:

```console
$ ls $(brew --prefix libmpdec)/lib/pkgconfig
ls: /opt/homebrew/opt/mpdecimal/lib/pkgconfig: No such file or directory
$ cd mpdecimal-2.5.1; find . | grep pkg
$
```

**Comment by ned-deily** [comment]
With the current 4.0.0 version, it appears both Homebrew and MacPorts ship them:

$ pkg-config libmpdec --cflags
-I/opt/homebrew/Cellar/mpdecimal/4.0.0/include
$ pkg-config libmpdec --libs
-L/opt/homebrew/Cellar/mpdecimal/4.0.0/lib -lmpdec -lm

...

$ pkg-config libmpdec --libs
-L/opt/macports/lib -lmpdec -lm

**Comment by erlend-aasland** [comment]
@zware are we still aiming for 3.13 for the first batch of items?

**Comment by erlend-aasland** [comment]
> In a quick test, it appeared that with `./configure --with-system-libmpdec` today, `pkg-config` info for `libmpdec` was not being used. If so, that should be corrected.

Resolved by:

- #115406

**Comment by zware** [comment]
> @zware are we still aiming for 3.13 for the first batch of items?

I would like to, but I don't know when I'm going to have a chance to get back to this.

**Comment by ned-deily** [comment]
There is an issue with unvendoring on macOS that will affect some users (and this may be something you ran into when testing, @erlend-aasland). For some reason, mpdecimal, for both 2.5.1 and 4.0.0, chooses to define `@rpath`-prefixed names for the macOS dynamic library install name for the shared libraries it builds. This can cause builds on macOS to fail in some cases unless additional action is taken.

By default, the libmpdec build produces both shared and a static libraries. On macOS, the shared library install name looks like this:
 
```
$ otool -L libmpdec.dylib
libmpdec.dylib:
	@rpath/libmpdec.4.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)

```

Note the `@rpath`. Typically, shared libraries built on macOS have an absolute path by default when installed, for example:

```
$ otool -L libsqlite3.dylib
libsqlite3.dylib:
	/opt/local/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.12)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)

```
An `@rpath` install name can be useful if you are building libraries that can be installed in arbitrary locations or are being embedded in something else but using an `@rpath`-based name requires additional configuration when building, like adding an `rpath` parameter to the linking of main executables.

To further cloud the issue, it appears that Homebrew, when building and installing its mpdecimal package, converts the `@rpath/libmpdec.4.dylib` install name to a conventional absolute path name:

```
$ otool -L /usr/local/Cellar/mpdecimal/4.0.0/lib/libmpdec.dylib
/usr/local/Cellar/mpdecimal/4.0.0/lib/libmpdec.dylib:
	/usr/local/opt/mpdecimal/lib/libmpdec.4.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)

```

and, at the moment, MacPorts does not:

```
$ otool -L /opt/macports/lib/libmpdec.dylib
/opt/macports/lib/libmpdec.dylib:
	@rpath/libmpdec.4.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
```

Also, like most similar packages providing libraries, mpdecimal by default installs both a shared library and a static (.a) library but the linker will normally always prefer a shared library when both are present in the same directory.  Both Homebrew and MacPorts install both.

AFAICT, this leaves the following scenarios as of now when building 3.13 with `--with-system-libmpdec` enabled:

1. If no third-party or private copy of libmpdec is available, the Python build fails with:

```
./Modules/_decimal/_decimal.c:38:10: fatal error: 'mpdecimal.h' file not found
#include <mpdecimal.h>
         ^~~~~~~~~~~~~
1 error generated.
```
2. If building with a current MacPorts copy of libmpdec or if building with a private copy that was built without explicitly disabling its shared library option (`--disable-shared`), the Python build will fail with something like:

```
[ERROR] _decimal failed to import: dlopen(/path/to/build/lib.macosx-14.4-x86_64-3.13/_decimal.cpython-313-darwin.so, 0x0002): Library not loaded: @rpath/libmpdec.4.dylib
  Referenced from: <A8A8EE60-CE66-309E-A108-472100134C51> /path/to/source/Modules/_decimal.cpython-313-darwin.so
  Reason: no LC_RPATH's found

Following modules built successfully but were removed because they could not be imported:
_decimal
```

3. If building with a current Homebrew copy of libmpdec, the Python build succeeds (because Homebrew removed the `@rpath` in the library install name) and links with the Homebrew installed shared libmpdec, not the static one.

Now there are various workarounds that I can think of to get around the situations where you are using an environment that contains a pre-built libmpdec with the default `@rpath`-named shared library, like if you are using MacPorts to supply all of the necessary third-party libs. But I can't think of any that doesn't involve some sort of kludge that requires more configuration options and/or creating alternate library directories. While probably most core developers building on macOS today use Homebrew, I believe there are some using MacPorts (besides me) and there are certainly downstream users in this situation as well as the MacPorts project itself. This segment of users could be addressed if the MacPorts project would opt to do what Homebrew is doing and remove the `@rpath` install name. That still leaves any other users building Python and its third-party libraries from scratch on macOS; they will be affected initially one way or another although they can adopt strategies like ensuring no libmpdec shared library is available to their builds.

The big question I have is how best to document this to minimize the impact on the various categories of users. At this point, I don't have good answers and I feel I can't spend any more time on this prior to feature code cutoff. But we shouldn't impose this change on users until we can fully explain its impact and how to workaround it.

**Comment by ned-deily** [comment]
(Opened MacPorts issue: https://trac.macports.org/ticket/69870)

**Comment by erlend-aasland** [comment]
Thank you for chiming in, Ned! I'll look into how to improve the docs here.

Even with the extra week before the feature freeze, it's going to be hard to land this nicely. I _may_ find some time for this later this week, but I can't (and won't, and should not) promise anything.

> There is an issue with unvendoring on macOS that will affect some users (and this may be something you ran into when testing, @erlend-aasland)

Yes, this may explain my issues from some weeks ago.

> If no third-party or private copy of libmpdec is available, the Python build fails with [...]

For this case, we should consider marking `_decimal` as a **missing** module instead of failing. After all, this is what we do with similar extension modules.

**Comment by ryandesign** [comment]
> (Opened MacPorts issue: https://trac.macports.org/ticket/69870)

I've merged the fix in MacPorts and reported the problem to the developer of mpdecimal by email; maybe they will fix it in an upcoming release and then we won't have to patch it anymore.

**Comment by ned-deily** [comment]
> I've merged the fix in MacPorts and reported the problem to the developer of mpdecimal by email; maybe they will fix it in an upcoming release and then we won't have to patch it anymore.

Thanks, @ryandesign! I've verified that the patched MacPorts library now works as expected.

**Comment by ned-deily** [comment]
BTW, unvendoring will also affect other platforms builds, in particular, the iOS build would now need to supply a `libmpdec` (FYI @freakboy3742).

**Comment by freakboy3742** [comment]
@ned-deily Thanks for the heads up. Reading back on the history - is the intention here that `libmpdec` will be shipped as a dynamic library, or statically linked into `_decimal` (or that will be left to platforms to decide)?

Also - tagging @mhsmith for the implications on Android. A quick search of the Android SDK didn't find `libmpdec`, but I might have missed something.

**Comment by mhsmith** [comment]
Yes, the Android build would need to supply its own copy as well, which should be easy enough. 

Our approach on Android has been to use dynamic linking for libraries which are large, or which third-party packages are likely to link against (SQLite and OpenSSL), and static linking for everything else. libmpdec would probably be in the static group.

**Comment by ned-deily** [comment]
The current vendored version is linked statically with _decimal but dynamic linking works too if the @rpath issue is dealt with. I don't think there's any particular preference. I'd probably stick with static.

**Comment by erlend-aasland** [comment]
@freakboy3742, @mhsmith: can you use the copy we provide in the cpython-sources-deps repo?

**Comment by erlend-aasland** [comment]
> The big question I have is how best to document this to minimize the impact on the various categories of users.

For most users, the devguide instructions will suffice. There is already a PR up for this.
For users who build their own mpdecimal library, we could ...:

1. add an item to the "Building" section of the What's New
2. add some text to `Mac/README.rst` and/or `Mac/BuildScript/README.rst`; the item of 1) could point to these resources

**Comment by mhsmith** [comment]
> can you use the copy we provide in the cpython-sources-deps repo?

Yes, probably.

**Comment by ned-deily** [comment]
> > can you use the copy we provide in the cpython-sources-deps repo?
> 
> Yes, probably.

Why would we want to do that? AFAIK, the cpython-sources-deps repo was created for and has only ever been used for Windows builds and may contain Windows-related patches. It's likely easier to use the original sources anyway.

**Comment by ned-deily** [comment]
Regardless, why create a new dependency with no apparent benefit? We've never used the cypthon-source-deps for anything other than Windows builds, say, for example, for macOS installer builds. Why start now?

**Comment by zware** [comment]
It's just an available option which is under our control and not subject to the whims of external hosts other than GitHub.

**Comment by freakboy3742** [comment]
> can you use the copy we provide in the cpython-sources-deps repo?

For iOS: almost certainly not without *some* patching. It's a configure-based project, so at a minimum it will need a patch to support the iOS and iOS-simulator host tags. That *might* be as simple as updating config.sub (the current version from CPython would do the job), but I'd need to dig in to be certain.

I've tried multiple times to get the iOS tags (especially the simulator ones) upstream into autoconf; I was *partially* successful with the 2024-01-01 release, but it's still missing the simulator tags. The autoconf contribution process appears to be a black hole... you email them a patch, and maybe they apply that patch at some point in the future, so you [watch the repo](http://git.savannah.gnu.org/cgit/autoconf.git/tree/build-aux/config.sub) to see if your patch has been applied. I haven't even received acknowledgement that I've *sent* a patch, let alone feedback on the patch.

**Comment by erlend-aasland** [comment]
> [...] The autoconf contribution process appears to be a black hole... you email them a patch, and maybe they apply that patch at some point in the future, so you [watch the repo](http://git.savannah.gnu.org/cgit/autoconf.git/tree/build-aux/config.sub) to see if your patch has been applied. I haven't even received acknowledgement that I've _sent_ a patch, let alone feedback on the patch.

We can solve this with https://discuss.python.org/t/pinning-gnu-autotools-using-the-github-container-registry/47437 
I'm aiming to complete that build container during the PyCon sprints.

**Comment by freakboy3742** [comment]
> > [...] The autoconf contribution process appears to be a black hole... you email them a patch, and maybe they apply that patch at some point in the future, so you [watch the repo](http://git.savannah.gnu.org/cgit/autoconf.git/tree/build-aux/config.sub) to see if your patch has been applied. I haven't even received acknowledgement that I've _sent_ a patch, let alone feedback on the patch.
> 
> We can solve this with https://discuss.python.org/t/pinning-gnu-autotools-using-the-github-container-registry/47437 I'm aiming to complete that build container during the PyCon sprints.

While I agree the devcontainer approach is worth pursing, unless I'm missing something, devcontainers won't address what I'm talking about here. 

The underlying issue is that third party libraries that have autoconf configuration *won't* support iOS out of the box, because autoconf doesn't have full support for iOS. As a result, any autoconf library that you want to use under iOS will require a patch of the `config.sub` file in that library's sources to add that support. We're talking about libmpdec here, but I currently have to patch [xz](https://github.com/beeware/cpython-apple-source-deps/blob/main/patch/xz-5.4.4.patch), [freetype](https://github.com/beeware/mobile-forge/blob/main/recipes/freetype/patches/config.patch), [libpng](https://github.com/beeware/mobile-forge/blob/main/recipes/libpng/patches/config.patch), and [libjpeg](https://github.com/beeware/mobile-forge/blob/main/recipes/libjpeg/patches/config.patch) in order to support CPython builds and the limited set of binary wheels that I'm currently maintaining. *Every* binary library using autoconf will have the same problem.

This is a problem that needs autoconf to accept a patch upstream to add iOS simulator support, so that third-party packages can update their `config.sub` to an official version that has simulator support, rather than needing to apply the same custom patch to every `config.sub` that has been vendored into a library's sources.

**Comment by erlend-aasland** [comment]
> [...] _Every_ binary library using autoconf will have the same problem.

Got it; thanks for the clarification! Well, let's hope your upstream patch makes it to the next GNU Autoconf release 🤞

**Comment by skirpichev** [comment]
It seems, that due to https://bugs.debian.org/1056785 - more projects now use ``_pydecimal`` implementation, that gets battle-tested.  Here is an example of a failure: https://github.com/aleaxit/gmpy/actions/runs/9153743194/job/25163188162 due to difference in the ``tp_name``: "decimal.Decimal" vs "Decimal".

**Comment by we-are-all-individuals** [comment]
Reaching out to the Debian CPython maintainer @doko42. It would be very nice to make mpdecimal available again in Debian. According to https://www.bytereef.org/mpdecimal/changelog.html the Sphinx issues no longer exist in version 4.0.0.

**Comment by vfazio** [comment]
Is the plan to still unvendor this if Debian doesn't reinstate the package?

**Comment by skirpichev** [comment]
Why Debian should be a special snowflake for CPython?  Referenced bug thread ignores any feedback, including comments from CPython core dev.  I think it's a Debian problem, not ours.

**Comment by vfazio** [comment]
Well, Debian is a major distro and the root of other distros like Ubuntu. But i guess they'll figure it out once Python fails to build

**Comment by skirpichev** [comment]
> Well, Debian is a major distro and the root of other distros like Ubuntu.

Say also thanks to people, who aren't part of the Debian maintainers now.

> But i guess they'll figure it out once Python fails to build

It will not fail.  IIUC, with `--with-system-libmpdec=no` & without bundled sources it will use the pure-Python decimal module, see above: https://github.com/python/cpython/issues/115119#issuecomment-2120314192.

Apparently they don't notice this.

**Comment by vfazio** [comment]
I missed the decimal -> _decimal or _pydecimal so thanks for pointing that out. I'll have to update my build scripts so i don't suffer the performance penalty

**Comment by skirpichev** [comment]
I don't think you can do here something.  Once the CPython will not bundle libmpdec - we will have no choice but fallback to the `_pydecimal` if `--with-system-libmpdec=no`.

Someone must do real job and package back the libmpdec for Debian.

**Comment by vfazio** [comment]
Hmm..

I'll have to look into it more. I'll was expecting to have to `--with-system-libmpdec=yes` and specify `LIBMPDEC_CFLAGS` and `LIBMPDEC_LIBS` to work around the calls to pkg-config. Worst case I compile and deploy the files to a custom directory and set `PKG_CONFIG_LIBDIR` and let the build system figure it out without the overrides.

Obviously this is not ideal, but until us Debian users get some traction on that issue, that's probably the best I can hope for.

When I get some spare time I'll test out a build with the vendored code nuked and see if the overrides work like I expect.

**Comment by skirpichev** [comment]
> I'll was expecting to have to --with-system-libmpdec=yes and specify LIBMPDEC_CFLAGS and LIBMPDEC_LIBS to work around the calls to pkg-config.

Ah, yes - that will work.

**Comment by tanzim** [comment]
What would be the guidance for folks building embedded distributions this case? Use relevant CFLAGS to relatively link to libmpdec shipped with the embedded distribution?

**Comment by erlend-aasland** [comment]
> Is the plan to still unvendor this if Debian doesn't reinstate the package?

Ondřej Surý has stepped up to reinstate and maintain mpdecimal in Debian:

https://salsa.debian.org/debian/mpdecimal

**Comment by vfazio** [comment]
> > Is the plan to still unvendor this if Debian doesn't reinstate the package?
> 
> Ondřej Surý has stepped up to reinstate and maintain mpdecimal in Debian:
> 
> https://salsa.debian.org/debian/mpdecimal

That's great! Thanks for the update.

**Comment by skirpichev** [comment]
@zware, it seems we are out of scheduled process in the 3.14 - as fallback to the bundled copy is still here.  Shall we remove that in beta?  Or we can skip this and just remove the mpdecimal copy in 3.15, together with the configure.ac fallback?

BTW, it seems the mpdecimal is in the Debian again.  Probably there are no good reasons to not follow to schedule in 3.15.  CC @erlend-aasland

**Comment by erlend-aasland** [comment]
@tanzim:

> What would be the guidance for folks building embedded distributions this case? Use relevant CFLAGS to relatively link to a copy of libmpdec shipped with the embedded distribution?

Yes, as you would do with any of the other third party dependencies.

@skirpichev:

My gut reaction would be to simply postpone everything with one release. That is, do in 3.15 what was planned for 3.14.

**Comment by skirpichev** [comment]
CC @hugovk, is this too late for 3.14 to remove fallback to bundled copy?  This wasn't announced in 3.13, but *removal* of bundled copy in 3.15 - was.  Sorry for asking, just to be sure.

Will you also suggest to shift planned stuff by one release?

**Comment by hugovk** [comment]
I've not read through the ~90 comments here, but seems this is not a bugfix and there's no pressing need for this in 3.14, so I suggest we do as @erlend-aasland said:

> My gut reaction would be to simply postpone everything with one release. That is, do in 3.15 what was planned for 3.14.

[Devguide](https://devguide.python.org/developer-workflow/development-cycle/#beta) reminder:

> After a first beta release is published, no new features are accepted. Only bug fixes and improvements to documentation and tests can now be committed. This is when core developers should concentrate on the task of fixing regressions and other new issues filed by users who have downloaded the alpha and beta releases.

**Comment by skirpichev** [comment]
> I've not read through the ~90 comments here

The evil plan is right in the description.

> seems this is not a bugfix

I'm in doubts, but rather "yes".

> and there's no pressing need for this in 3.14, so I suggest we do as @erlend-aasland said

Ok, then I'll prepare a documentation patch for 3.13/14 and remove fallback in 3.15.

**Comment by AA-Turner** [comment]
@skirpichev I'm a little confused, we shouldn't change anything in 3.14 at this point, but the 3.15 development cycle is open. Do you intend to change anything in Python 3.15 relating to the vendored libmpdec?

I've no objections to delaying the removal of the vendored sources to 3.16, I'd just like to understand the rationale.

A

**Comment by skirpichev** [comment]
Ok, pr's are ready for review:
* #133997 - mostly docs changes, to backport
* #134078 - removal of the fallback (must be enabled by ``--without-system-libmpdec``)

**Comment by AA-Turner** [comment]
> remove [the] bundled copy in [Python] 3.15, as planned, in one shot

We advertised the following to users:

> [Pending Removal in Python 3.15](https://docs.python.org/3/whatsnew/3.13.html#id9)
> * The bundled copy of `libmpdecimal`.

> Build Changes:
> * The `configure` option --with-system-libmpdec now defaults to `yes`. The bundled copy of `libmpdecimal` will be removed in Python 3.15.

We didn't mention removing the implicit fallback, so personally I think it's OK to remove both in one go. Ubuntu 26.04 (to be released c. 1 month before Python 3.15b1) will have `mpdecimal` sources, which will make building easier.

However, removing the fallback in 3.15 and then removing the bundled sources in 3.16 is the more conservative position.

A

**Comment by skirpichev** [comment]
> Ubuntu 26.04 (to be released c. 1 month before Python 3.15b1) will have mpdecimal sources, which will make building easier.

This will be not immediately available in gh action runners.

> However, removing the fallback in 3.15 and then removing the bundled sources in 3.16 is the more conservative position.

I think more core devs in the thread are for that option, thus I withdraw my pr with removal of the bundled copy.  Or should we ask someone else?

**Comment by edmorley** [comment]
> Ubuntu 26.04 (to be released c. 1 month before Python 3.15b1) will have `mpdecimal` sources, which will make building easier.

Hi! We build CPython releases for all supported Ubuntu LTS versions (so currently 22.04 + 24.04, and next year 26.04 too). By the time of Python 3.16's release, Ubunu 22.04 LTS should be out of standard support, so we won't have to support that. However, that still leaves 24.04 that from the sounds of it won't have an `mpdecimal` package available? Has anyone asked if Canonical would be willing to add `mpdecimal` to older LTSes too?

**Comment by skirpichev** [comment]
It's possible to use [PPA for PHP](https://launchpad.net/~ondrej/+archive/ubuntu/php) to get libmpdec on Ubuntu 24.04.  See https://github.com/python/cpython/pull/133964.

**Comment by skirpichev** [comment]
CC @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
This is a question to @hugovk.

**Comment by skirpichev** [comment]
FYI, I started https://discuss.python.org/t/101829 to discuss a possible removal of the pure-Python version.

**Comment by serhiy-storchaka** [comment]
There is a regression in 3.15 -- #139994.

**Comment by skirpichev** [comment]
> There is a regression in 3.15 -- https://github.com/python/cpython/issues/139994.

@serhiy-storchaka, it's not a regression.  There is no way to make required (by this issue) changes without breaking of backward compatibility.

If you think, that warning is not enough, we could consider a ./configure error: https://github.com/python/cpython/issues/139994#issuecomment-3401344696.  The major problem is that people, not interested in math at all - will (usually) have to *add* workaround to build CPython: https://github.com/python/cpython/issues/139994#issuecomment-3401454900.

**Comment by zware** [comment]
With the merge of GH-133964, this is finally done!  There are some minor cleanup opportunities remaining, but I'm closing this issue.  Thanks @skirpichev for driving it to completion!

**Comment by asottile** [comment]
👋 (noticing this because of nightly builds for deadsnakes) -- removing the bundled copy makes python unbuildable on ubuntu 24.04 because there is no system `libmpdec` there

**Comment by asottile** [comment]
(fwiw I would prefer waiting to remove the bundled copy until 24.04 is end-of-lifed if possible.  26.04 has a proper package for this moving forward)

**Comment by vstinner** [comment]
Python GitHub Action used this repository to get libmpdec on Ubuntu 24.04:

```sh
# Workaround missing libmpdec-dev on ubuntu 24.04:
# https://launchpad.net/~ondrej/+archive/ubuntu/php
# https://deb.sury.org/
sudo add-apt-repository ppa:ondrej/php
apt-get update
apt-get -yq --no-install-recommends install libmpdec-dev
```

After the recent Ubuntu network outage, the recipe was replaced with:

```sh
# Workaround missing libmpdec-dev on ubuntu 24.04 by building mpdecimal
# from source. ppa:ondrej/php (launchpad.net) are unreliable 
# (https://status.canonical.com) so fetch the tarball directly
# from the upstream host.
# https://www.bytereef.org/mpdecimal/
MPDECIMAL_VERSION=4.0.1
curl -fsSL "https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-${MPDECIMAL_VERSION}.tar.gz" \
    | tar -xz -C /tmp
(cd "/tmp/mpdecimal-${MPDECIMAL_VERSION}" \
    && ./configure --prefix=/usr/local \
    && make -j"$(nproc)" \
    && make install)
ldconfig
```

**Comment by eli-schwartz** [comment]
Why not just backport the libmpdec package?

**Comment by asottile** [comment]
@vstinner that doesn't help -- I need to build entirely from source on launchpad machines
@eli-schwartz I don't control the ubuntu repositories just the deadsnakes ones.  unless you're suggesting "backporting" via revendoring in a patch?

**Comment by serhiy-storchaka** [comment]
Simply do not support Python 3.16 on Ubuntu 24.04. Or live with pure Python implementation of decimal.

**Comment by asottile** [comment]
@serhiy-storchaka heh I mean neither of those are great -- I liked your idea here fwiw https://github.com/python/cpython/issues/139994#issuecomment-3396771640

**Comment by zware** [comment]
I consider the disappearance of `libmpdec{,-dev}` in Ubuntu 24.04 to be a bug in that version of Ubuntu; lobby them to fix it.

**Comment by asottile** [comment]
it's an LTS, they don't add new packages.  I've tried many times

**Comment by asottile** [comment]
it's also not present in debian:bookworm

**Comment by vstinner** [comment]
Can't you add libmpdev in deadsnakes PPA?

**Comment by eli-schwartz** [comment]
> @eli-schwartz I don't control the ubuntu repositories just the deadsnakes ones. unless you're suggesting "backporting" via revendoring in a patch?

I quite literally mean backport the `*.deb` packaging format package for a dpkg package named "libmpdec". If I'd meant reverting a patch to revendor the source directory I'd say "forward port the libmpdec sources from older python", which is the opposite of a backport.

The repository that you control is deadsnakes, hence backport from Ubuntu 26.04 to deadsnakes.

**Comment by skirpichev** [comment]
> (noticing this because of nightly builds for deadsnakes) -- removing the bundled copy makes python unbuildable on ubuntu 24.04 because there is no system libmpdec there

@asottile, could you please point to build logs or elaborate a bit exact reason of failure?  Missing libmpdec shouldn't prevent CPython 3.16 from build:
```
$ ./configure -q
configure: WARNING: no system libmpdec found; falling back to pure-Python version for the decimal module
$ make -s
Written build/lib.linux-x86_64-3.16/_sysconfigdata__linux_x86_64-linux-gnu.py
Written build/lib.linux-x86_64-3.16/_sysconfig_vars__linux_x86_64-linux-gnu.json
The necessary bits to build these optional modules were not found:
_decimal
To find the necessary bits, look in configure.ac and config.log.

Checked 116 modules (37 built-in, 77 shared, 1 n/a on linux-x86_64, 0 disabled, 1 missing, 0 failed on import)
$ ./python -m test test_decimal
Using random seed: 1990606034
0:00:00 load avg: 2.12 Run 1 test sequentially in a single process
0:00:00 load avg: 2.12 [1/1] test_decimal
C tests skipped: no module named _decimal.
0:00:15 load avg: 2.24 [1/1] test_decimal passed

== Tests result: SUCCESS ==

1 test OK.

Total duration: 15.6 sec
Total tests: run=579 skipped=198
Total test files: run=1/1
Result: SUCCESS
```

It might be that differences of pure-Python decimal module wrt the C extension break some your CI tests.  In this case, please open issues.

> I consider the disappearance of libmpdec{,-dev} in Ubuntu 24.04 to be a bug in that version of Ubuntu; lobby them to fix it.

They blindly follow unprofessional actions of Debian maintainers: https://bugs.debian.org/1056785.

BTW, this is not a problem for ubuntu 22.04 or 26.04.  Tentative schedule for new GA images: https://github.com/actions/runner-images/issues/13964#issuecomment-4360396351 

Edit:

> I would prefer waiting to remove the bundled copy until 24.04 is end-of-lifed

That means April 2034, i.e ~10 years.  Any good reasons for this huge delay, given that the libmpdec is available in PPA and it's trivial to build it from sources?

**Comment by edmorley** [comment]
> I consider the disappearance of `libmpdec{,-dev}` in Ubuntu 24.04 to be a bug in that version of Ubuntu; lobby them to fix it.

Opened https://support-portal.canonical.com/tickets/00448718

**Comment by edmorley** [comment]
> Opened https://support-portal.canonical.com/tickets/00448718

Which resulted in a (currently in-progress) SRU request to add `libmpdec-dev` to noble, here:
https://bugs.launchpad.net/ubuntu/+source/mpdecimal/+bug/2167730
