### ISSUE TITLE
Rewrite asyncio subprocesses without child watchers 

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#120804]
### Tasks
- [x] Remove child watchers (excludes threaded and pidfd watcher) #120805
- [x] Remove `get_child_watcher` and `set_child_watcher` https://github.com/python/cpython/pull/120818
- [x] Remove threaded and pidfd watcher https://github.com/python/cpython/pull/120893
- [x] Remove abc of it https://github.com/python/cpython/pull/120893
- [x] Add documentation regarding it and news entry https://github.com/python/cpython/pull/120895

Each task item will be done in a separate PR and news entry will be added when all of this is done otherwise it will be confusing for users. 

### Linked PRs
* gh-120805
* gh-120818
* gh-120893
* gh-120895
* gh-121124
