### ISSUE TITLE
Add `PyType_GetBaseByToken` function with `Py_tp_token` slot

### ISSUE THREAD

**Issue by neonene** [python/cpython#124153]
This issue implements a proposal related to PEP-489 and PEP-630.

**Decision:**

* https://github.com/capi-workgroup/decisions/issues/34

**TODO:**

- [x] Implement the feature
- [x] Use it in `_PyStgInfo_FromType_NoState()` in `_ctypes.c`
- [x] Ensure no performance regression in `PyType_GetModuleByDef()` and other functions affected by this feature on Windows PGO builds

**TODO (optional):**

- [x] Replace `PyType_GetModuleByDef()` in `defdict_or()` (`_collectionsmodule.c`)
- [x] Replace `_PyType_GetModuleByDef2()` in `_decimal.c`
- [x] Remove `_PyType_GetModuleByDef2()`

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

* https://github.com/encukou/abi3/issues/19
* https://discuss.python.org/t/55598

### Linked PRs
* gh-121079
* gh-124163
* gh-124261
* gh-124323
* gh-124488
* gh-141644

**Comment by encukou** [comment]
The first PR is merged. Keeping this open for the other TODO items.

**Comment by neonene** [comment]
Completed. Thank you for allowing me to follow up.
