### ISSUE TITLE
resource tracker destroys shared memory segments when other processes should still have valid access

### ISSUE THREAD

**Issue by applio** [python/cpython#82300]
BPO | [38119](https://bugs.python.org/issue38119)
--- | :---
Nosy | @pitrou, @applio, @pablogsal, @maggyero, @vinay0410, @JSmith-BitFlipper, @keven425, @TKaluza
PRs | <li>python/cpython#15989</li><li>python/cpython#21516</li><li>python/cpython#23174</li>
Files | <li>[mprt_monkeypatch.py](https://bugs.python.org/file49859/mprt_monkeypatch.py "Uploaded as text/plain at 2021-03-08.19:22:16 by turicas")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/applio'
closed_at = None
created_at = <Date 2019-09-11.15:58:26.817>
labels = ['3.8', 'type-bug', 'library', '3.9', '3.10']
title = 'resource tracker destroys shared memory segments when other processes should still have valid access'
updated_at = <Date 2022-02-10.20:53:56.777>
user = 'https://github.com/applio'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-10.20:53:56.777>
actor = 'maggyero'
assignee = 'davin'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-09-11.15:58:26.817>
creator = 'davin'
dependencies = []
files = ['49859']
hgrepos = []
issue_num = 38119
keywords = ['patch']
message_count = 14.0
messages = ['351960', '352050', '374434', '374939', '374944', '374951', '374954', '374956', '374958', '374974', '387606', '388287', '390198', '412440']
nosy_count = 12.0
nosy_names = ['pitrou', 'steve.newcomb', 'turicas', 'davin', 'pablogsal', 'maggyero', 'vinay0410', 'damian.barabonkov', 'keven425', 'davfelsen', 'jdogzz-g5', 'timka']
pr_nums = ['15989', '21516', '23174']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38119'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

## TODO list:

* [x] Add a `track=True` parameter to SharedMemory (#110778 did this) so it can be disabled by the user.
* [ ] It still needs covering in the What's New in 3.13 documentation.
* [ ] Verify and make other documentation improvements as necessary as alluded by @ambv below in https://github.com/python/cpython/issues/82300#issuecomment-1336166761 - It sounded like we've got docs implying that resources outlive the process _by default_ which was not what the implementation ever did.

### Linked PRs
* gh-110778

**Comment by root-11** [comment]
Is the use case included where the shared memory object lives longer than the subprocess and where gc respects that shm shall not be gc'ed?

Outline:
1. main starts a subprocess with a queue for inter inter-proc message exchange.
2. main sleeps.
3. subprocess creates a shared memory block
4. subprocess posts the shm name (str) on the inter-proc queue
5. subprocess finishes and exits.
6. main is still busy.
7. main reads the name from the queue
8. main accesses to the shared_memory block
9. main closes the shared_memory.

If not, then I can add the test case here?

**Comment by root-11** [comment]
I've added a post here: https://discuss.python.org/t/multiprocessing-with-shared-memory-potential-fix-for-bug-82300/15012
It works on windows.

I hope it's to some use?

**Comment by buzmeg** [comment]
Context: This is all on Linux  (Ubuntu 22.04.1 LTS) so I'm going to avoid talking about Windows

Dumb question: Isn't SharedMemory supposed to work if a completely different language does the shm_open()?

I do an shm_open() in a zig process and then tried to attach and close a SharedMemory() from Python.  The resource tracker then complains with:

```
λ /usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
```

and unlinks the shared memory.

That's a touch ... surprising.

If multiprocessing isn't supposed to handle this case, could somebody point me at a more cooperative Python module?

Thanks.

**Comment by ambv** [comment]
Both removing the resource tracking as well as introducing the reference counting are backwards incompatible. In the former case, the danger of breaking users' software is much lesser though because:

1. if the parent process Python code was using SharedMemoryManager anyway, the blocks will get cleaned up anyway;
2. if the parent process Python code was exposing the shared memory block to other programming languages, it will continue working as expected;
3. if the parent process Python code was using an explicit name for the shared memory block, restarting the process will fail with a clear error that the name is used;
4. if the parent process Python code creates a new implicitly named shared memory block every time, you have a memory leak in the system.

Only cases 3. and 4. are disruptive to the user, both in trivially fixable ways. If we adopted the solution from GH-23174, the situation would be more tricky because:

1. processes unaware that the first 4 bytes are special would misuse the shared memory block created with the patched `multiprocessing.shared_memory`;
2. and vice versa: Python would be unable to access (via `multiprocessing.shared_memory`) shared memory blocks created by other programming languages;
3. a shared memory block must be able to outlive its creating process, this is not only expected but also currently documented in `multiprocessing.shared_memory` as a valid use case;
4. the user can still say `track_resource=False` and thus cause memory leaks.

Therefore, I think what we should do is the following:

1. Redo GH-15989 to disable resource tracking of shared memory blocks *by default* but add an optional `track_resource=` as GH-23174 is doing. The default should be false.
2. The documentation is *already* recommending use of SharedMemoryManager and *already* says that "As a resource for sharing data across processes, shared memory blocks may outlive the original process that created them. When one process no longer needs access to a shared memory block that might still be needed by other processes, the close() method should be called.  When a shared memory block is no longer needed by any process, the unlink() method should be called to ensure proper cleanup.", implying that this process is not happening by default.

**Comment by satishskamath** [comment]
Any updates on what exactly is going on, did they implement it the way it is described here in #15989 ?

**Comment by wtdcode** [comment]
Any update on this?

**Comment by arhadthedev** [comment]
@pitrou, @gpshead (as multiprocessing experts)

**Comment by applio** [comment]
I fully agree with @ambv in https://github.com/python/cpython/issues/82300#issuecomment-1336166761.

It will be very nice to finally get this fixed.

**Comment by alonbl** [comment]
A trivial use case of shared memory is not supported and requires teaks that may be incompatible in future. Why isn't this fixed?
1. Apply resource tracking to shared memory only if `create=True`.
2. or: `close()` method to unregister.
3. or: remove the resource tracking as it not actually required.

**Comment by pan324** [comment]
At the very least something like `track=True` would not interfere with existing code whatsoever and be very much appreciated.

**Comment by buzmeg** [comment]
Can we *please* get a "track=True" default on the initializer and fix the semantics on close when "track=False"?  

This issue has been open almost 4 years.  I commented on it almost a year ago.

Adding "track=True" in the init and having those of us who don't want tracking set it to False is:

1) an effective solution for those of us who need this
2) backward compatible
3) Simple enough that it should be able to get approved (nothing more complicated seems to be able to get through discussion)

Thanks.

**Comment by gvanrossum** [comment]
> This issue has been open almost 4 years.

It looks like no core dev exists who feels confident they understand this API well enough to change this API without accidentally breaking existing code. If someone here is still listening who can submit an implementation, please go ahead! It's much easier as a core dev to find time for a code review than to find time to implement an idea from scratch (even if the idea is about changing existing code).

**Comment by pitrou** [comment]
@pan324 @buzmeg A PR would be welcome.

**Comment by buzmeg** [comment]
@pan324 Thanks for putting in the PR.  You saved me the time and effort.  Let me know if there is something you need me to do.

**Comment by gvanrossum** [comment]
Start jumping when alpha 2 is released without this.

**Comment by buzmeg** [comment]
@gvanrossum You said I should start jumping up and down when Alpha 2 is released without this.

Alpha 2 has been released without this.  I'm jumping up and down.  :smile: 

@pitrou @pan324

**Comment by gpshead** [comment]
The PR adding the `track=True` keyword argument feature to `multiprocessing.shared_memory.SharedMemory` to allow tracking to be disabled by passing `False` is in for 3.13.

TODO list (i'll put this in the opening comment up top for visibility):

* It still needs covering in the What's New documentation
* I suspect there are other documentation improvements to be made, based on https://github.com/python/cpython/issues/82300#issuecomment-1336166761 it sounded like we've got docs implying that resources outlive the process _by default_ which was not what the implementation ever did.

Given the way POSIX "works" (or doesn't, depending on your point of view) I think this is all we can meaningfully do given the platform behavior.

**Comment by gpshead** [comment]
Thanks for all the discussion & proposed PRs everybody.

**Comment by buzmeg** [comment]
@gpshead  Thanks for shepherding this in.

**Comment by gvanrossum** [comment]
Thanks Greg. I was out of my depth here…

**Comment by tanrbobanr** [comment]
Glad to see this get resolved. For a backward-compatible fix, I have found that the below works well:

```py
import sys
import threading
from multiprocessing import resource_tracker as _mprt
from multiprocessing import shared_memory as _mpshm


if sys.version_info >= (3, 13):
    SharedMemory = _mpshm.SharedMemory
else:
    class SharedMemory(_mpshm.SharedMemory):
        __lock = threading.Lock()

        def __init__(
            self, name: str | None = None, create: bool = False,
            size: int = 0, *, track: bool = True
        ) -> None:
            self._track = track

            # if tracking, normal init will suffice
            if track:
                return super().__init__(name=name, create=create, size=size)

            # lock so that other threads don't attempt to use the
            # register function during this time
            with self.__lock:
                # temporarily disable registration during initialization
                orig_register = _mprt.register
                _mprt.register = self.__tmp_register

                # initialize; ensure original register function is
                # re-instated
                try:
                    super().__init__(name=name, create=create, size=size)
                finally:
                    _mprt.register = orig_register

        @staticmethod
        def __tmp_register(*args, **kwargs) -> None:
            return

        def unlink(self) -> None:
            if _mpshm._USE_POSIX and self._name:
                _mpshm._posixshmem.shm_unlink(self._name)
                if self._track:
                    _mprt.unregister(self._name, "shared_memory")
```
This is likely *slightly* less efficient than simply copying the 3.13 version of `SharedMemory`, but is a lot smaller (especially given only a few things need to happen in order for tracking to be avoided).

**Comment by mbrinz** [comment]
my application is using ShareableList() which makes use of SharedMemory() => shared_memory.py .. actually I was glad to see that the track parameter got added to SharedMemory() as of 3.13 onwwards, but I was wondering why this track parameter was not added to ShareableList() also ... doing this will help standalone client processes to close without destroying the ShareableList() of the server process.
Below you see the necessary adaptations in the code for this:

`class ShareableList:

    def __init__(self, sequence=None, *, name=None, track=True):

        if name is None or sequence is not None:
	
            self.shm = SharedMemory(name, create=True, size=requested_size, track=track)
        else:
            self.shm = SharedMemory(name, track=track)
`
