### ISSUE TITLE
sqlite3: improve scoping of functions in the sqlite3 extension module

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#92206]
Clean up scoping/namespace by moving some functions. This will also help future refactoring I've got planned.

- [x] pysqlite_step(): #92207
  Defined in: Modules/_sqlite/util.c
  Used only in: Modules/_sqlite/cursor.c

- [x] bind params helpers: #92250
  Defined in: Modules/_sqlite/statement.c
  Used only in: Modules/_sqlite/cursor.c

- [x] pysqlite_connection_register_cursor(): #92212
  Defined in: Modules/_sqlite/connection.c
  Used only in: Modules/_sqlite/cursor.c

- [x] pysqlite_statement_reset(): #92241
  Defined in: Modules/_sqlite/statement.c
  Used only in: Modules/_sqlite/cursor.c

- [x] pysqlite_statement_mark_dirty(): #92260
  Defined in: Modules/_sqlite/statement.c
  Used only in: Modules/_sqlite/cursor.c

**Comment by erlend-aasland** [comment]
Thanks for helping, Jelle!
