### ISSUE TITLE
Tasklist test issue

### ISSUE THREAD

**Issue by ezio-melotti** [python/cpython#97021]
```[tasklist]
### Tasks
- [ ] This is an example of task list
- [ ] <- the gray circle indicates draft issues
- [ ] You can convert drafts to actual issues from there ->
- [ ] You can also remove tasklist items from there ->
- [ ] You can also link actual issues, like the next one:
- [ ] https://github.com/python/cpython/issues/91420
- [ ] From the UI you might have to paste the full URL
- [ ] Pull requests can't be linked (yet)
- [x] https://github.com/zware/test/issues/1
- [ ] ^- Cross repo/organization issue links also appear to work
```

**Comment by CAM-Gerlach** [comment]
I can't seem to "convert drafts to actual issues", including by clicking on the text or the button, so I'm not sure how that is supposed to work. Also, cross repo/org issues don't list the repo or org, so that's rather confusing. And without PRs (much less nested subissues, categories, etc. it doesn't perhaps seems as useful as I thought it would be—as I've used it and most often seen them used on Python-org repos, they are most commonly used to serve as a common issue for many relatively small/related PRs.

**Comment by ezio-melotti** [comment]
> I can't seem to "convert drafts to actual issues", including by clicking on the text or the button, so I'm not sure how that is supposed to work.

If you hover on a task a button with 3 dots should appear on the right.  If you click on that and select "Convert to issue" it should create a new issue.
![image](https://user-images.githubusercontent.com/25624924/191906478-863c480c-3ccf-46ee-840d-fbdb6b2cae55.png)

> Also, cross repo/org issues don't list the repo or org, so that's rather confusing. 

Indeed, I would expect `zware/test#1` instead of just `#1`.  FWIW if you hover on the issue you can see the repo in the popup that appears.

> And without PRs

Apparently these are coming.  I also reiterated the suggestion of providing a way to link PRs to issue that doesn't automatically close the issue when a PR is merged (see https://github.com/python/bedevere/issues/501).

> nested subissues, categories

IIUC the way to handle this is to create an issue A with a tasklist that includes B, and then add another tasklist in B.  This doesn't currently show the nesting in A's tasklist though, but it might be added later, possibly together with other meta information.

cc @omerbensaadon

**Comment by CAM-Gerlach** [comment]
> If you hover on a task a button with 3 dots should appear on the right. If you click on that and select "Convert to issue" it should create a new issue.

I'm not seeing the three dots after I hover. Maybe it requires permissions I don't have as a triager (though I'm not sure why, and that would be fixed by my proposal)?

![image](https://user-images.githubusercontent.com/17051931/192024509-58ed5115-67d9-4b98-81a7-6ca82e8a3dcb.png)

> I also reiterated the suggestion of providing a way to link PRs to issue that doesn't automatically close the issue when a PR is merged (see https://github.com/python/bedevere/issues/501).

That would indeed be very useful as we've discussed elsewhere (https://github.com/python/devguide/pull/855#discussion_r948513454), and also replicate the old BPO functionality

> IIUC the way to handle this is to create an issue A with a tasklist that includes B, and then add another tasklist in B.

I see; that's not ideal, but workable (I initially didn't include nested issues in #95913 myself)

**Comment by CAM-Gerlach** [comment]
Seems like it is a permissions limitation, which I suppose in hindsight makes sense (since does modify the post source content) but may be surprising to users, and does tend to limit this feature's usability. However, the proposal in python/core-workflow#460 would work around that (as well as for existing Checklists).

**Comment by arhadthedev** [comment]
The issue is no longer relevant. Bedevere settled down with the plain list. Here is gh-104584 as an example (note how verbose GitHub renders issue IDs inside list items):
So this issue can be closed.
![](https://github.com/python/cpython/assets/4881073/57720d19-361f-4b6f-a2fa-69681c7dd255)

So this issue can be closed.

**Comment by arhadthedev** [comment]
Moreover, GitHub retires the format we experimented with:

![](https://github.com/python/cpython/assets/4881073/2baa21dc-72e9-43ae-bc6f-2739e574a739)

To keep CPython issues working, I'm going through https://github.com/python/cpython/issues?q=tasklist replacing the tasklists with the new Bedevere format.

**Comment by arhadthedev** [comment]
Done with careful rewriting and removal of misgenerated duplicates. Thus, closing this issue.

**Comment by ezio-melotti** [comment]
Thanks!
