### ISSUE TITLE
Meta issue for cleaning up import system cruft

### ISSUE THREAD

**Issue by warsaw** [python/cpython#97850]
This is a meta issue tracking all the things that need to be cleaned up in the import system.  From removing long deprecated APIs to migrating internal access to `__spec__`, we'll have several task lists for each related set of clean ups.

@brettcannon @ericsnowcurrently for visibility.

# Removing deprecated APIs

Over in [What's New for Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html#pending-removal-in-python-3-12) there's a long list of things that have been deprecated long enough that they can be removed in Python 3.12.  Here's that task list for tracking purposes.  Watch for linked PRs (maybe one big one or many small ones -- we'll see!).

@brettcannon @ericsnowcurrently for visibility.

- [x] [importlib.find_loader()](https://docs.python.org/3.11/library/importlib.html#importlib.find_loader)
- [x] [importlib.util.module_for_loader()](https://docs.python.org/3.11/library/importlib.html#importlib.util.module_for_loader)
- [x] ```importlib.util.set_loader_wrapper()```
- [x] ```importlib.util.set_package_wrapper()```
- [x] [importlib.abc.Loader.module_repr()](https://docs.python.org/3.11/library/importlib.html#importlib.abc.Loader.module_repr) (3.12: #97876)
- [x] [importlib.abc.MetaPathFinder.find_module()](https://docs.python.org/3.11/library/importlib.html#importlib.abc.MetaPathFinder.find_module)
- [x] [importlib.abc.MetaPathFinder.find_module()](https://docs.python.org/3.11/library/importlib.html#importlib.abc.MetaPathFinder.find_module)
- [x] [importlib.abc.PathEntryFinder.find_loader()](https://docs.python.org/3.11/library/importlib.html#importlib.abc.PathEntryFinder.find_loader)
- [x] [importlib.abc.PathEntryFinder.find_module()](https://docs.python.org/3.11/library/importlib.html#importlib.abc.PathEntryFinder.find_module)
- [x] ```importlib.machinery.BuiltinImporter.find_module()```
- [x] ```importlib.machinery.BuiltinLoader.module_repr()``` (3.12: #97876)
- [x] [importlib.machinery.FileFinder.find_loader()](https://docs.python.org/3.11/library/importlib.html#importlib.machinery.FileFinder.find_loader)
- [x] ```importlib.machinery.FileFinder.find_module()```
- [x] ```importlib.machinery.FrozenImporter.find_module()```
- [x] ```importlib.machinery.FrozenLoader.module_repr()``` (3.12: #97876)
- [x] [importlib.machinery.PathFinder.find_module()](https://docs.python.org/3.11/library/importlib.html#importlib.machinery.PathFinder.find_module)
- [x] ```importlib.machinery.WindowsRegistryFinder.find_module()```
- [x] Remove `pkgutil.ImpImporter` (3.12: already deprecated)
- [x] Remove `pkgutil.ImpLoader`
- [x] Remove the `imp` module (3.12: #98040)
- [x] ```importlib.abc.Finder```

# Update docs

- [ ] Make sure examples and details from [PEP 302](https://peps.python.org/pep-0302/) are covered in the importlib docs (/cc @Yhg1s )
- [x] Remove https://docs.python.org/3/reference/import.html#open-issues ([PR](https://github.com/python/cpython/pull/97935))
- [ ] It would be really nice to have a diagram.
- [ ] (import_machinery.rst) how about a section devoted just to the attributes of modules and packages, perhaps expanding upon or supplanting the related entries in the data model reference page?
- [ ] runpy, pkgutil, et al in the library manual should all get “See Also” links at the top pointing to the new import system section.
- [ ] Add more explanation regarding the different ways in which `__main__` is initialized?
- [ ] Add more info on `__main__` quirks/pitfalls (i.e. copy from [PEP 395](https://www.python.org/dev/peps/pep-0395)).

# Missing deprecations

Here's a list of related APIs that have not yet been deprecated, but should be.  We'll deprecate them in 3.12 and remove them in 3.14.

- [x] `pkgutil.find_loader()`
- [x] `pkgutil.get_loader()` (or it needs to be reimplemented to not use `find_loader()`)

Other:

- [x] #103999

* PR: gh-98520

* PR: gh-104133

* PR: gh-104134

* PR: gh-108719

* PR: gh-108723

* PR: gh-119656

* PR: gh-128601

* PR: gh-128602

* PR: gh-128654

* PR: gh-128655

* PR: gh-128895

* PR: gh-128896

* PR: gh-129855

* PR: gh-130013

* PR: gh-130017

* PR: gh-131149

* PR: gh-142205

**Comment by sobolevn** [comment]
I've removed `importlib.utils.set_loader`, `importlib.utils.set_package`, and
`importlib.utils.module_for_loader` from `importlib.utils` in https://github.com/python/cpython/pull/97898 🎉

**Comment by sobolevn** [comment]
I've created a PR: https://github.com/python/cpython/pull/98520
to complete these two tasks:

> - [ ] pkgutil.find_loader()
> - [ ] pkgutil.get_loader() (or it needs to be reimplemented to not use find_loader())

**Comment by brettcannon** [comment]
FYI https://github.com/python/cpython/issues/64138 is a tracking issue for `pkgutil` all up.

**Comment by warsaw** [comment]
From the meta checklist:

> Deprecate pkgutil.find_loader()

I kind of think we're okay here, at least for 3.12.  This uses `importlib.util.find_spec()` so I feel like it's not so urgent to deprecate and actually probably has some utility.

> Deprecate pkgutil.get_loader()

Similarly, I'm not sure this even needs to be deprecated.  It is implemented in terms of the above, and thus `find_spec()`, and it has some potentially useful wrapper semantics.

I'm going to mark both issues as complete and *not* deprecate it in 3.12.

**Comment by warsaw** [comment]
@brettcannon @ericsnowcurrently - I think this PR is ready for review.  I feel good that we've implemented all the removals we need for 3.12.  Like the other issues, we can address the doc updates after beta 1.

**Comment by warsaw** [comment]
The removal branch has been merged, but I'm leaving this meta issue open for now so we can address the documentation checklist during the beta cycle.

**Comment by ericsnowcurrently** [comment]
Thanks again for tackling this, @warsaw!

**Comment by hugovk** [comment]
For the `imp` module, I created issues for most of the 71 projects in the PyPI top 5k (listed at https://github.com/python/cpython/pull/98573#issuecomment-1507963962), where I could find their tracker. And some already had issues.

I've checked off projects which had already fixed but not yet released, or have fixed since I created the issue, or where the project is unmaintained or otherwise abandoned and a fix is unlikely in any case.

Currently 24/71 (34%) are checked off. In the issue I pointed to the [3.11 `imp` docs](https://docs.python.org/3.11/library/imp.html) which have suggestions of how to upgrade each functions/constants, and most seemed fine with that so far, except for [one](https://github.com/apple/coremltools/issues/1846#issuecomment-1530180451) noting  `imp.load_source` has no suggestions.

---

* [ ] 1. [ansiwrap](https://pypi.org/project/ansiwrap/) - not updated since 2019, already reported: https://github.com/jonathaneunice/ansiwrap/issues/17 and has 3.11 test failures: https://github.com/jonathaneunice/ansiwrap/issues/18
* [x] 2. [asttokens](https://pypi.org/project/asttokens/) - only in a file used as data for a test - reported: https://github.com/gristlabs/asttokens/issues/108
* [x] 3. [audioread](https://pypi.org/project/audioread/) - already replaced: https://github.com/beetbox/audioread/pull/128
* [x] 4. [auth](https://pypi.org/project/auth/) - imported but not used, merged PR: https://github.com/ourway/auth/pull/9
* [ ] 5. [autopep8](https://pypi.org/project/autopep8/) - used in tests, reported: https://github.com/hhatto/autopep8/issues/683
* [x] 6. [boto](https://pypi.org/project/boto/) - "This package is no longer maintained and has been replaced by [Boto3](https://github.com/boto/boto3)"
* [ ] 7. [cement](https://pypi.org/project/cement/) - already reported: https://github.com/datafolklabs/cement/issues/386
* [ ] 8. [coremltools](https://pypi.org/project/coremltools/) - reported: https://github.com/apple/coremltools/issues/1846
* [ ] 9. [crochet](https://pypi.org/project/crochet/)
* [x] 10. [Cython](https://pypi.org/project/Cython/) - looks like compat aleady added
* [ ] 11. [databricks-cli](https://pypi.org/project/databricks-cli/) - reported: https://github.com/databricks/databricks-cli/issues/631
* [x] 12. [datalab](https://pypi.org/project/datalab/) - project is deprecated, [repo is archived](https://github.com/googledatalab/pydatalab)
* [x] 13. [diff-match-patch](https://pypi.org/project/diff-match-patch/) - used in tests, reported: https://github.com/diff-match-patch-python/diff-match-patch/issues/5
* [x] 14. [distribute](https://pypi.org/project/distribute/) - not updated since 2013, "This package is a simple compatibility layer that installs Setuptools 0.7+."
* [x] 15. [django_compressor](https://pypi.org/project/django_compressor/) - https://github.com/django-compressor/django-compressor/issues/1185
* [ ] 16. [django-compat](https://pypi.org/project/django-compat/) - not updated in 6 years but reported: https://github.com/arteria/django-compat/issues/67
* [ ] 17. [django-configurations](https://pypi.org/project/django-configurations/) - reported: https://github.com/jazzband/django-configurations/issues/358
* [x] 18. [django-heroku](https://pypi.org/project/django-heroku/) - not updated in 5 years and repo archived
* [ ] 19. [dominate](https://pypi.org/project/dominate/) - reported https://github.com/Knio/dominate/issues/172
* [ ] 20. [flasgger](https://pypi.org/project/flasgger/) - reported https://github.com/flasgger/flasgger/issues/563
* [ ] 21. [Flask-AppBuilder](https://pypi.org/project/Flask-AppBuilder/) - reported https://github.com/dpgaspar/Flask-AppBuilder/issues/2027
* [ ] 22. [future](https://pypi.org/project/future/)
* [ ] 23. [gevent](https://pypi.org/project/gevent/) - already has compat (via `_imp`)
* [ ] 24. [glom](https://pypi.org/project/glom/) - reported https://github.com/mahmoud/glom/issues/261
* [ ] 25. [gsutil](https://pypi.org/project/gsutil/) - reported https://github.com/GoogleCloudPlatform/gsutil/issues/1695, with PR: https://github.com/mtth/hdfs/pull/192
* [ ] 26. [hdfs](https://pypi.org/project/hdfs/) - already reported: https://github.com/mtth/hdfs/issues/191
* [x] 27. [hyper](https://pypi.org/project/hyper/) - project archived
* [ ] 28. [IMAPClient](https://pypi.org/project/IMAPClient/) - in tests, reported https://github.com/mjs/imapclient/issues/504
* [x] 29. [invoke](https://pypi.org/project/invoke/) - fixed and released: https://github.com/pyinvoke/invoke/pull/919
* [ ] 30. [j2cli](https://pypi.org/project/j2cli/) - reported https://github.com/kolypto/j2cli/issues/80
* [x] 31. [joblib](https://pypi.org/project/joblib/) - test file removed
* [ ] 32. [Kivy](https://pypi.org/project/Kivy/) - reported https://github.com/kivy/kivy/issues/8225
* [ ] 33. [logilab-common](https://pypi.org/project/logilab-common/)
* [ ] 34. [lxml](https://pypi.org/project/lxml/) - reported https://bugs.launchpad.net/lxml/+bug/2018137
* [x] 35. [markdown2](https://pypi.org/project/markdown2/) in tests, reported https://github.com/trentm/python-markdown2/issues/510
* [ ] 36. [mercurial](https://pypi.org/project/mercurial/)
* [ ] 37. [metaflow](https://pypi.org/project/metaflow/) - reported https://github.com/Netflix/metaflow/issues/1380
* [ ] 38. [ml_collections](https://pypi.org/project/ml_collections/) - reported https://github.com/google/ml_collections/issues/24
* [ ] 39. [mysql-connector](https://pypi.org/project/mysql-connector/)
* [ ] 40. [mysql-connector-python-rf](https://pypi.org/project/mysql-connector-python-rf/)
* [x] 41. [nose](https://pypi.org/project/nose/) - unmaintained
* [ ] 42. [numba](https://pypi.org/project/numba/) - in tests, reported https://github.com/numba/numba/issues/8933
* [ ] 43. [oletools](https://pypi.org/project/oletools/) - reported https://github.com/decalage2/oletools/issues/813
* [ ] 44. [os_sys](https://pypi.org/project/os_sys/) - reported https://github.com/Matthijs990/os-sys-github/issues/4
* [x] 45. [Paste](https://pypi.org/project/Paste/) - reported https://github.com/cdent/paste/issues/75
* [x] 46. [pathtools](https://pypi.org/project/pathtools/) - not released in 12 years
* [ ] 47. [pbr](https://pypi.org/project/pbr/)
* [x] 48. [pep562](https://pypi.org/project/pep562/) - reported https://github.com/facelessuser/pep562/issues/13, but no longer receiving active support
* [ ] 49. [pex](https://pypi.org/project/pex/) - reported https://github.com/pantsbuild/pex/issues/2137
* [x] 50. [ptvsd](https://pypi.org/project/ptvsd/) - project is deprecated, repo is archived
* [ ] 51. [pydevd-pycharm](https://pypi.org/project/pydevd-pycharm/)
* [ ] 52. [pydoop](https://pypi.org/project/pydoop/) - in tests, reported https://github.com/crs4/pydoop/issues/371
* [ ] 53. [pyexcel](https://pypi.org/project/pyexcel/) - in tests, reported https://github.com/pyexcel/pyexcel/issues/274
* [ ] 54. [pyinstaller](https://pypi.org/project/pyinstaller/) - reported https://github.com/pyinstaller/pyinstaller/issues/7601
* [x] 55. [pynose](https://pypi.org/project/pynose/) - reported https://github.com/mdmintz/pynose/issues/1
* [ ] 56. [pyrepl](https://pypi.org/project/pyrepl/)
* [ ] 57. [pysaml2](https://pypi.org/project/pysaml2/) - reported https://github.com/IdentityPython/pysaml2/issues/904
* [ ] 58. [pytest-shutil](https://pypi.org/project/pytest-shutil/) - reported https://github.com/man-group/pytest-plugins/issues/216
* [x] 59. [PyXB](https://pypi.org/project/PyXB/) - project only works up to 3.7 https://github.com/pabigot/pyxb/issues/100#issuecomment-1526932482 and repo archived
* [ ] 60. [reportlab](https://pypi.org/project/reportlab/)
* [ ] 61. [snapshottest](https://pypi.org/project/snapshottest/) - reported https://github.com/syrusakbary/snapshottest/issues/166
* [ ] 62. [social-auth-core](https://pypi.org/project/social-auth-core/) - reported https://github.com/python-social-auth/social-core/issues/789
* [ ] 63. [sox](https://pypi.org/project/sox/) - reported https://github.com/rabitt/pysox/issues/158
* [ ] 64. [sqlalchemy-migrate](https://pypi.org/project/sqlalchemy-migrate/)
* [ ] 65. [stone](https://pypi.org/project/stone/) - reported https://github.com/dropbox/stone/issues/295
* [x] 66. [strip-hints](https://pypi.org/project/strip-hints/) - reported https://github.com/abarker/strip-hints/issues/19
* [ ] 67. [Theano](https://pypi.org/project/Theano/)
* [x] 68. [Twisted](https://pypi.org/project/Twisted/) - fixed pending release https://github.com/twisted/twisted/pull/11712
* [x] 69. [twofish](https://pypi.org/project/twofish/) - already reported in 2016 but no updates since 2013 https://github.com/keybase/python-twofish/issues/4
* [ ] 70. [uwsgi](https://pypi.org/project/uwsgi/) - reported https://github.com/unbit/uwsgi/issues/2534
* [ ] 71. [workflow](https://pypi.org/project/workflow/) - reported https://github.com/inveniosoftware-contrib/workflow/issues/68

**Comment by mdmintz** [comment]
Due to ``nose`` being unmaintained (number 41 in your list), that's why there's ``pynose`` now (number 55 in your list).
It's a complete drop-in replacement for all occurrences. (Let me know if that isn't the case.)

**Comment by hugovk** [comment]
> Edit 2023-11-05: 36/71 (52%)

We're now over 50% of those in the checklist.

**Comment by hugovk** [comment]
> Edit 2024-06-07: 55/71 (78%)

We're now at 78% (fixed or unmaintained/abandoned).

**Comment by tomasr8** [comment]
Related issue: https://github.com/python/cpython/issues/121604

Here's a couple more things that might need attention:

- (docs) [ResourceLoader](https://docs.python.org/3.14/library/importlib.html#importlib.abc.ResourceLoader) is deprecated and recommends [ResourceReader](https://docs.python.org/3.14/library/importlib.resources.abc.html#importlib.resources.abc.ResourceReader) as an alternative which is itself deprecated. We should skip this extra link and recommend [TraversableResources](https://docs.python.org/3.14/library/importlib.resources.abc.html#importlib.resources.abc.TraversableResources) directly.
- [ResourceReader](https://docs.python.org/3.14/library/importlib.resources.abc.html#importlib.resources.abc.ResourceReader) is deprecated and supposed to be removed in 3.14 but does not raise `DeprecationWarning` - I can add a Deprecation warning in https://github.com/python/cpython/pull/128007 and we should probably update the docs to say that it'll be removed in 3.16 instead.
- [Loader.load_module](https://docs.python.org/3.14/library/importlib.html#importlib.abc.Loader.load_module) is deprecated with the deprecation stating it will be removed in 3.12. Should we try to remove this method in 3.14? If not, we should update the deprecation message.

In general, lots of methods/attributes are marked as deprecated in the docs for a long time (for example: [DEBUG_BYTECODE_SUFFIXES](https://docs.python.org/3.14/library/importlib.html#importlib.machinery.DEBUG_BYTECODE_SUFFIXES) is deprecated since 3.5). It's probably not a good idea to remove them now (especially those that don't yet raise a `DeprecationWarning`), but we could mark them as `deprecated-removed` instead, planning to remove them in 3.16?

Would like to know your thoughts on what to do about these :)

**Comment by brettcannon** [comment]
> * (docs) [ResourceLoader](https://docs.python.org/3.14/library/importlib.html#importlib.abc.ResourceLoader) is deprecated and recommends [ResourceReader](https://docs.python.org/3.14/library/importlib.resources.abc.html#importlib.resources.abc.ResourceReader) as an alternative which is itself deprecated. We should skip this extra link and recommend [TraversableResources](https://docs.python.org/3.14/library/importlib.resources.abc.html#importlib.resources.abc.TraversableResources) directly.

👍



> * [ResourceReader](https://docs.python.org/3.14/library/importlib.resources.abc.html#importlib.resources.abc.ResourceReader) is deprecated and supposed to be removed in 3.14 but does not raise `DeprecationWarning` - I can add a Deprecation warning in [gh-121604: Make sure all deprecated items in importlib raise DeprecationWarning #128007](https://github.com/python/cpython/pull/128007) and we should probably update the docs to say that it'll be removed in 3.16 instead.

That's a @jaraco question.



> * [Loader.load_module](https://docs.python.org/3.14/library/importlib.html#importlib.abc.Loader.load_module) is deprecated with the deprecation stating it will be removed in 3.12. Should we try to remove this method in 3.14? If not, we should update the deprecation message.

If it has been documented as deprecated for 5 releases **and** raising an exception for as long, then it can come out.

> but we could mark them as `deprecated-removed` instead, planning to remove them in 3.16?

We should keep it all around for 5 releases of being documented as deprecated as well as raising an exception. There's no rush here as we are just trying to nudge people to better APIs long-term more than avoiding buggy code that's blocking some other change.

**Comment by jaraco** [comment]
> > * [ResourceReader](https://docs.python.org/3.14/library/importlib.resources.abc.html#importlib.resources.abc.ResourceReader) is deprecated and supposed to be removed in 3.14 but does not raise `DeprecationWarning` - I can add a Deprecation warning in [gh-121604: Make sure all deprecated items in importlib raise DeprecationWarning #128007](https://github.com/python/cpython/pull/128007) and we should probably update the docs to say that it'll be removed in 3.16 instead.
> 
> That's a @jaraco question.

Thanks for the tag.

I'm not certain `ResourceReader` is even deprecated.

It was in https://github.com/python/cpython/issues/93963 that `importlib.abc.ResourceReader` (note not `importlib.resources.abc`) was deprecated (and subsequently removed). But the deprecation notices were added to the docs for `importlib.resources.abc`.

It seems this discontinuity has led to previous confusion (e.g. https://github.com/python/cpython/issues/107352), though it doesn't seem the discontinuity was resolved.

I'm not sure if there was ever an intention to deprecate `ResourceReader`. It does seem to make sense to do so, given that `TraversableResources` is to be preferred. Since we've had the deprecation notice in the docs for a while, and if we extend the deadline to Python 3.16, that should provide adequate notice of a removal, though we may choose to extend that deadline.

On the other hand, maybe it makes sense to simply change the documentation to reflect the deprecation without any scheduled removal. That would be my preference. Do you have an opinion @encukou?

**Comment by tomasr8** [comment]
Thanks to both for your answers!

@jaraco If I understand correctly, you lean more towards keeping `ResourceReader` deprecated? If that is the case, should we add a `DeprecationWarning` as well? Currently, the deprecation is only mentioned in the docs. As Brett says, we can also extend the deprecation timeline in the docs to 3.14 + 5.

**Comment by tomasr8** [comment]
Ok I can remove the scheduled removal from the docs of `ResourceReader` :+1: 

@encukou since you mentioned not bothering people with warnings, what's your opinion on this issue (and the linked PR): https://github.com/python/cpython/issues/121604 Should all the mentioned items also raise deprecation warnings?

**Comment by jaraco** [comment]
> @jaraco If I understand correctly, you lean more towards keeping `ResourceReader` deprecated? If that is the case, should we add a `DeprecationWarning` as well? Currently, the deprecation is only mentioned in the docs. As Brett says, we can also extend the deprecation timeline in the docs to 3.14 + 5.

I do, but I'm not confident there's a clear path to deprecate, because although the interface is deprecated, it's an interface that's used both by providers and consumers of that interface. Even its replacement subclasses that interface, so it's not even obvious to me that a deprecation warning is possible. Sounds like it's best to just leave it documented. Thanks.

**Comment by encukou** [comment]
> what's your opinion on this issue (and the linked PR): https://github.com/python/cpython/issues/121604

My first impression: The deprecation code seems like a bigger maintenance burden than the deprecated API itself; better to just leave it alone. Let's deprecate things that are dangerous or misleading, not just old and limited.
But, I don't think my personal opinion should carry much weight here.

**Comment by warsaw** [comment]
> Let's deprecate things that are dangerous or misleading
... or unmaintainable.

If it doesn't match any of those criteria then agreed there's no urgency to remove them and break code.

**Comment by tomasr8** [comment]
Thanks everyone for your comments! :)

I created https://github.com/python/cpython/pull/128601 and https://github.com/python/cpython/pull/128602 to update the deprecations in the docs.
